// <auto-generated />
using System;
using CarBiding;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarBiding.Migrations
{
    [DbContext(typeof(CarDBContext))]
    partial class CarDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CarBiding.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ImageMiniID")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkToAuction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeAuctionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeAuctionStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ImageMiniID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarBiding.Core.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("CarBiding.Car", b =>
                {
                    b.HasOne("CarBiding.Core.Image", "ImageMini")
                        .WithMany()
                        .HasForeignKey("ImageMiniID");

                    b.Navigation("ImageMini");
                });

            modelBuilder.Entity("CarBiding.Core.Image", b =>
                {
                    b.HasOne("CarBiding.Car", null)
                        .WithMany("Images")
                        .HasForeignKey("CarID");
                });

            modelBuilder.Entity("CarBiding.Car", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
